// The right rail: the conversation's files — uploaded, generated by the
// model's write_file tool, or pulled from the corpus. Click to read; upload
// goes through the same endpoint the model's tools use.

import { LitElement, css, html } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { WorkspaceFile, listFiles, readFile, uploadFile } from "./api.js";

@customElement("workspace-panel")
export class WorkspacePanel extends LitElement {
  static styles = css`
    :host { display: flex; flex-direction: column; height: 100%; width: 320px;
            background: #0a0d12; border-left: 1px solid #21262d; }
    h3 { margin: 0; padding: 14px 16px 8px; font-size: 13px; text-transform: uppercase;
         letter-spacing: 0.05em; color: #8b949e; display: flex; justify-content: space-between; }
    h3 button { background: none; border: 1px solid #21262d; color: #b6bec8;
                border-radius: 6px; cursor: pointer; font: inherit; padding: 2px 8px; }
    .list { flex: 1; overflow-y: auto; }
    .file { padding: 8px 16px; cursor: pointer; font-size: 13.5px; }
    .file:hover { background: #161b22; }
    .file .meta { color: #8b949e; font-size: 11.5px; }
    .view { flex: 1; display: flex; flex-direction: column; min-height: 0; }
    .view pre { flex: 1; overflow: auto; margin: 0; padding: 12px 16px; font-size: 12.5px;
                background: #0e1116; white-space: pre-wrap; }
    .back { align-self: flex-start; margin: 8px 16px; background: none; color: #ea580c;
            border: 0; cursor: pointer; font: inherit; }
    .none { padding: 16px; color: #8b949e; font-size: 13px; }
  `;

  @property() threadId = "";
  @state() private files: WorkspaceFile[] = [];
  @state() private open = "";
  @state() private content = "";

  async updated(changed: Map<string, unknown>) {
    if (changed.has("threadId")) { this.open = ""; await this.refresh(); }
  }

  async refresh() {
    this.files = this.threadId === "" ? [] : await listFiles(this.threadId).catch(() => []);
  }

  private async show(name: string) {
    const file = await readFile(this.threadId, name);
    this.open = name;
    this.content = file.content;
  }

  private pick() {
    const input = document.createElement("input");
    input.type = "file";
    input.onchange = async () => {
      const f = input.files?.[0];
      if (!f) return;
      await uploadFile(this.threadId, f.name, await f.text());
      await this.refresh();
    };
    input.click();
  }

  render() {
    if (this.open !== "") {
      return html`<div class="view">
        <button class="back" @click=${() => { this.open = ""; }}>← Files</button>
        <pre>${this.content}</pre>
      </div>`;
    }
    return html`
      <h3>Workspace ${this.threadId === "" ? "" : html`<button @click=${this.pick}>Upload</button>`}</h3>
      <div class="list">
        ${this.threadId === "" ? html`<div class="none">Open a conversation first.</div>` : ""}
        ${this.threadId !== "" && this.files.length === 0 ? html`<div class="none">No files in this conversation.</div>` : ""}
        ${this.files.map((f) => html`
          <div class="file" @click=${() => this.show(f.name)}>
            ${f.name}
            <div class="meta">${f.mime} · ${f.origin}</div>
          </div>`)}
      </div>
    `;
  }
}
